spring:
  docker:
    compose:
      file: ics/compose.yaml
      enabled: true
  application:
    name: ics
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ics
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${MY_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimensions: 1536
  mail:
    debug: true
    host: smtp.gmail.com
    port: 587
    username: otunabochidubem@gmail.com
    password: zczapcmagyiwyvlo
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
        starttls:
            enable: true
            required: true
  debug: true